const { utf8ToHash160 } = require("../hash")
const {
  STRUCTURED_COIN_OBJECT,
  STRUCTURED_COIN_OBJECT_OPTIONS,
  STRUCTURED_COIN_OBJECT_AVAILABLE_MODES,
  STRUCTURED_COIN_OBJECT_DIRECTORY_NAMES
} = require("./StructuredCurrencyImport");

// Attestation Defaults
const STRUCTURED_COIN_OBJECT_VERSION = 0

const STRUCTURED_COIN_OBJECT_HASH = [utf8ToHash160(STRUCTURED_COIN_OBJECT).toString('hex')]
const STRUCTURED_COIN_OBJECT_OPTIONS_HASH = [utf8ToHash160(STRUCTURED_COIN_OBJECT_OPTIONS).toString('hex')]
const STRUCTURED_COIN_OBJECT_AVAILABLE_MODES_HASH = [utf8ToHash160(STRUCTURED_COIN_OBJECT_AVAILABLE_MODES).toString('hex')]
const STRUCTURED_COIN_OBJECT_DIRECTORY_NAMES_HASH = [utf8ToHash160(STRUCTURED_COIN_OBJECT_DIRECTORY_NAMES).toString('hex')]

module.exports = {
  STRUCTURED_COIN_OBJECT_VERSION,
  STRUCTURED_COIN_OBJECT_HASH,
  STRUCTURED_COIN_OBJECT_OPTIONS_HASH,
  STRUCTURED_COIN_OBJECT_AVAILABLE_MODES_HASH,
  STRUCTURED_COIN_OBJECT_DIRECTORY_NAMES_HASH
}