const { utf8ToHash160 } = require("../hash")

// Payment Request Defaults
const VERUS_PAYMENT_REQUEST_VERSION = 0

const VERUS_PAYMENT_REQUEST = 'payment_request:vrsc'
const VERUS_PAYMENT_REQUEST_PAYLOAD = 'payload'

const VERUS_PAYMENT_REQUEST_HASH = [utf8ToHash160(VERUS_PAYMENT_REQUEST).toString('hex')]
const VERUS_PAYMENT_REQUEST_PAYLOAD_HASH = [utf8ToHash160(VERUS_PAYMENT_REQUEST_PAYLOAD).toString('hex')]

module.exports = {
  VERUS_PAYMENT_REQUEST_VERSION,
  VERUS_PAYMENT_REQUEST,
  VERUS_PAYMENT_REQUEST_PAYLOAD,
  VERUS_PAYMENT_REQUEST_HASH,
  VERUS_PAYMENT_REQUEST_PAYLOAD_HASH
}